[package]
name = "problem-016"
version = "0.1.0"
authors = ["Ahmad Fz <ahmad.f.zadeh@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
